DROP TABLE IF EXISTS sources CASCADE;
DROP TABLE IF EXISTS media CASCADE;
DROP TABLE IF EXISTS texts CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS canvases CASCADE;
DROP TABLE IF EXISTS series CASCADE;
DROP TABLE IF EXISTS works CASCADE;
DROP TABLE IF EXISTS captions CASCADE;

DROP TYPE IF EXISTS m_type CASCADE;
CREATE TYPE m_type AS ENUM ('sound', 'video', 'image');

CREATE TABLE works (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(4096) NOT NULL
);

CREATE TABLE series (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    series_id BIGINT,
    title VARCHAR(4096) NOT NULL
);

CREATE TABLE canvases (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL,
    last_edit TIMESTAMPTZ NOT NULL
);

CREATE TABLE groups (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    canvas_id BIGINT NOT NULL,
    idx INTEGER NOT NULL,
    swap_direction BOOLEAN NOT NULL
);

CREATE TABLE texts (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    content VARCHAR(4194304)
);

CREATE TABLE media (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    media_type m_type NOT NULL
);

CREATE TABLE sources (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    media_id BIGINT NOT NULL,
    link VARCHAR(4096) NOT NULL
);

CREATE TABLE captions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    content VARCHAR(4194304)
);

ALTER TABLE series
ADD CONSTRAINT series_parent_fk
FOREIGN KEY (series_id) REFERENCES series(id);

ALTER TABLE canvases
ADD CONSTRAINT canvases_work_fk
FOREIGN KEY (work_id) REFERENCES works(id);

ALTER TABLE groups
ADD CONSTRAINT groups_parent_fk
FOREIGN KEY (parent_id) REFERENCES groups(id);

ALTER TABLE groups
ADD CONSTRAINT groups_canvas_fk
FOREIGN KEY (canvas_id) REFERENCES canvases(id);

ALTER TABLE texts
ADD CONSTRAINT texts_group_fk
FOREIGN KEY (group_id) REFERENCES groups(id);

ALTER TABLE media
ADD CONSTRAINT media_group_fk
FOREIGN KEY (group_id) REFERENCES groups(id);

ALTER TABLE sources
ADD CONSTRAINT sources_media_fk
FOREIGN KEY (media_id) REFERENCES media(id);
